---
# tasks file for php
- name: install php-fpm
  apt:
    pkg:
      - php
      - php-cli
      - php-fpm
      - php-json
      - php-mysql
      - php-zip
      - php-gd
      - php-mbstring
      - php-curl
      - php-xml
      - php-pear
      - php-bcmath
    update_cache: true

- name: Copy php-fmp config file to remote host
  copy:
    src: "{{ tmp_dir }}/www.conf"
    dest: "/etc/php/8.1/fpm/pool.d/www.conf"
    backup: true  

- name: copy index.php
  copy:
    src: "{{ tmp_dir }}/index.php"
    dest: "/var/www/html/index.php"


- name: restart php-fpm
  service:
    name: php8.1-fpm.service
    state: restarted
